---

- name: restart netatalk
  service: name=netatalk state=restarted

- name: Restart network
  service: name=networking state=restarted

- name: Restart and enable dnsmasq
  service: name=dnsmasq state=restarted enabled=yes
  listen: Restart network
