---
- name: Disable wlan0
  cron:
    special_time: reboot
    job: "sudo ifdown wlan0"

- name: Partition external hard disk and mount it to media directory
  include: prepare_volume.yml
  when: marpi_perform_repartitioning

- name: Setup Netatalk to create an Time Machine compatible network disk
  include: netatalk.yml
